add test file
gitpay-ru/workforce-mvp pull request #16
Opened 2023-03-18 10:54 UTC by RomaPetuhov

2023-03-22 19:00 UTC, vkocheryzhkin commented
@RomaPetuhov 
I think we can leave only 3 input files and test_tasks.py. Other files seems not required. 🍎

2023-03-22 19:00 UTC, vkocheryzhkin requested changes

2023-03-22 19:00 UTC, vkocheryzhkin commented on project/tests/test_actual_time.py
> +    'application_octet-stream_result_blob_http___31.133.120.7_8004_2c3abe0d-72a2-4b01-929c-c558d2b71b5d')
@RomaPetuhov we can remove this file right?

2023-04-12 11:36 UTC, vkocheryzhkin approved these changes, later dismissed

2023-05-23 08:00 UTC, vkocheryzhkin approved these changes

2023-05-23 08:02 UTC, RomaPetuhov commented
@adavydenko

2023-05-25 12:07 UTC, merged